# Generated by Django 5.2.3 on 2025-06-16 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao_estimada', models.PositiveIntegerField(help_text='Duração em minutos')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.box')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(blank=True, null=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atividade')),
                ('sessao_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.sessaoservico')),
            ],
        ),
    ]
