# Generated by Django 5.2.3 on 2025-06-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filial_box_filial_funcionario_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.filial'),
        ),
    ]
